class BeastShrine:
    """
    Superclass for both beasts and shrines
    """
    def __init__(self, id, name, orbs, region, lat, long):
        self.id=id
        self.name=name
        self.orbs=orbs
        self.region=region
        self.lat=lat
        self.long=long
    
    
class Beast(BeastShrine):
    def __init__(self, id, name, region, lat, long):
        super().__init__(id, name, 4, region, lat, long)
        
    def __repr__(self):
        return 'Beast(id={}, name={!r}, region={!r})'\
            .format(self.id, self.name, self.region)

class Shrine(BeastShrine):
    def __init__(self, id, name, trial, quest, blessing, tos, beast, region, lat, long):
        super().__init__(id, name, 1, region, lat, long)
        self.trial=trial
        self.quest=quest
        self.blessing=blessing
        self.tos=tos
        self.beast=beast
    def __repr__(self):
        return 'Shrine(id={}, name={!r}, trial={!r}, quest={!r}, blessing={}, tos={!r}, beast={!r}, region={!r})'\
            .format(self.id, self.name, self.trial, self.quest, self.blessing, self.tos, self.beast, self.region)
            
#Copied and modified from https://github.com/rekyuu/msrta_gen/blob/master/lib/msrta_gen/definitions.ex
beasts=[
Beast(
    id=0,
    name='Vah Medoh',
    region='Tabantha',
    lat=1864,
    long=-3614,
),
Beast(
    id=1,
    name='Vah Naboris',
    region='Wasteland',
    lat=-2636,
    long=-2110,
),
Beast(
    id=2,
    name='Vah Ruta',
    region='Lanayru',
    lat=-242,
    long=2985,
),
Beast(
    id=3,
    name='Vah Rudania',
    region='Eldin',
    lat=2491,
    long=-2538,
)
]

shrines=[
Shrine(
    id=0,
    name='Tutsuwa Nima',
    trial='A Major Test of Strength',
    quest='The Spring of Power',
    blessing=False,
    tos='major',
    beast=None,
    region='Akkala',
    lat=2705,
    long=3778,
),
Shrine(
    id=1,
    name='Dah Hesho',
    trial='A Minor Test of Strength',
    quest=None,
    blessing=False,
    tos='minor',
    beast=None,
    region='Akkala',
    lat=1303,
    long=3900,
),
Shrine(
    id=2,
    name="Ke'nai Shakah",
    trial='A Modest Test of Strength',
    quest=None,
    blessing=False,
    tos='modest',
    beast=None,
    region='Akkala',
    lat=857,
    long=4194,
),
Shrine(
    id=3,
    name='Katosa Aug',
    trial='Katosa Aug Apparatus',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Akkala',
    lat=2730,
    long=4296,
),
Shrine(
    id=4,
    name='Ritaag Zumo',
    trial="Ritaag Zumo's Blessing",
    quest='Into the Vortex',
    blessing=True,
    tos=None,
    beast=None,
    region='Akkala',
    lat=2128,
    long=4525,
),
Shrine(
    id=5,
    name="Tu Ka'loh",
    trial="Tu Ka'loh's Blessing",
    quest='Trial of the Labyrinth',
    blessing=True,
    tos=None,
    beast=None,
    region='Akkala',
    lat=3710,
    long=4655,
),
Shrine(
    id=6,
    name='Ze Kasho',
    trial='Ze Kasho Apparatus',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Akkala',
    lat=1668,
    long=3027,
),
Shrine(
    id=7,
    name='Zuna Kai',
    trial="Zuna Kai's Blessing",
    quest="The Skull's Eye",
    blessing=True,
    tos=None,
    beast=None,
    region='Akkala',
    lat=3420,
    long=3324,
),
Shrine(
    id=8,
    name="Saas Ko'sah",
    trial='A Major Test of Strength',
    quest=None,
    blessing=False,
    tos='major',
    beast=None,
    region='Central',
    lat=1159,
    long=-147,
),
Shrine(
    id=9,
    name='Katah Chuki',
    trial='A Minor Test of Strength',
    quest=None,
    blessing=False,
    tos='minor',
    beast=None,
    region='Central',
    lat=345,
    long=-636,
),
Shrine(
    id=10,
    name='Noya Neha',
    trial='A Minor Test of Strength',
    quest=None,
    blessing=False,
    tos='minor',
    beast=None,
    region='Central',
    lat=624,
    long=-951,
),
Shrine(
    id=11,
    name='Namika Ozz',
    trial='A Modest Test of Strength',
    quest=None,
    blessing=False,
    tos='modest',
    beast=None,
    region='Central',
    lat=821,
    long=761,
),
Shrine(
    id=12,
    name='Wahgo Katta',
    trial='Metal Connections',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Central',
    lat=-1007,
    long=345,
),
Shrine(
    id=13,
    name='Rota Ooh',
    trial='Passing of the Gates',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Central',
    lat=-1310,
    long=-1563,
),
Shrine(
    id=14,
    name='Kaya Wan',
    trial='Shields from Water',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Central',
    lat=-188,
    long=824,
),
Shrine(
    id=15,
    name="Kaam Ya'tak",
    trial='Test of Power',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Central',
    lat=-716,
    long=-968,
),
Shrine(
    id=16,
    name='Hila Rao',
    trial='Drifting',
    quest='Watch Out for the Flowers',
    blessing=False,
    tos=None,
    beast=None,
    region='Dueling Peaks',
    lat=-838,
    long=855,
),
Shrine(
    id=17,
    name='Lakna Rokee',
    trial="Lakna Rokee's Blessing",
    quest='The Stolen Heirloom',
    blessing=True,
    tos=None,
    beast=None,
    region='Dueling Peaks',
    lat=-972,
    long=2040,
),
Shrine(
    id=18,
    name="Ta'loh Naeg",
    trial="Ta'loh Naeg's Teaching",
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Dueling Peaks',
    lat=-890,
    long=1842,
),
Shrine(
    id=19,
    name='Ha Dahamar',
    trial='The Water Guides',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Dueling Peaks',
    lat=-1919,
    long=1666,
),
Shrine(
    id=20,
    name='Bosh Kala',
    trial='The Wind Guides You',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Dueling Peaks',
    lat=-1659,
    long=87,
),
Shrine(
    id=21,
    name='Ree Dahee',
    trial='Timing is Critical',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Dueling Peaks',
    lat=-1844,
    long=1272,
),
Shrine(
    id=22,
    name='Toto Sah',
    trial='Toto Sah Apparatus',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Dueling Peaks',
    lat=-2474,
    long=1846,
),
Shrine(
    id=23,
    name='Shee Vaneer',
    trial='Twin Memories',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Dueling Peaks',
    lat=-1938,
    long=1265,
),
Shrine(
    id=24,
    name='Shee Venath',
    trial='Twin Memories',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Dueling Peaks',
    lat=-1850,
    long=1244,
),
Shrine(
    id=25,
    name='Qua Raym',
    trial='A Balanced Approach',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Eldin',
    lat=1517,
    long=1821,
),
Shrine(
    id=26,
    name='Shora Hah',
    trial='Blue Flame',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Eldin',
    lat=3118,
    long=1535,
),
Shrine(
    id=27,
    name='Gorae Torr',
    trial="Gorae Torr's Blessing",
    quest='The Gut Check Challenge',
    blessing=True,
    tos=None,
    beast=None,
    region='Eldin',
    lat=3457,
    long=2662,
),
Shrine(
    id=28,
    name='Kayra Mah',
    trial='Greedy Hill',
    quest="A Brother's Roast",
    blessing=False,
    tos=None,
    beast=None,
    region='Eldin',
    lat=2040,
    long=2077,
),
Shrine(
    id=29,
    name="Mo'a Keet",
    trial='Metal Makes a Path',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Eldin',
    lat=1166,
    long=2724,
),
Shrine(
    id=30,
    name='Tah Muhl',
    trial='Passing the Flame',
    quest='A Landscape of a Stable',
    blessing=False,
    tos=None,
    beast=None,
    region='Eldin',
    lat=941,
    long=2301,
),
Shrine(
    id=31,
    name='Sah Dahaj',
    trial='Power of Fire',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Eldin',
    lat=1581,
    long=2665,
),
Shrine(
    id=32,
    name='Daqa Koh',
    trial='Stalled Flight',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Eldin',
    lat=2328,
    long=2066,
),
Shrine(
    id=33,
    name="Shae Mo'sah",
    trial='Swinging Flames',
    quest=False,
    blessing=False,
    tos=False,
    beast=False,
    region='Eldin',
    lat=2562,
    long=1757,
),
Shrine(
    id=34,
    name='Muwo Jeem',
    trial='A Modest Test of Strength',
    quest=None,
    blessing=False,
    tos='modest',
    beast=None,
    region='Faron',
    lat=-3308,
    long=3658,
),
Shrine(
    id=35,
    name='Yah Rin',
    trial='A Weighty Decision',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Faron',
    lat=-3311,
    long=2833,
),
Shrine(
    id=36,
    name='Korgu Chideh',
    trial="Korgu Chideh's Blessing",
    quest='Stranded on Eventide',
    blessing=True,
    tos=None,
    beast=None,
    region='Faron',
    lat=-3772,
    long=4737,
),
Shrine(
    id=37,
    name='Shai Utoh',
    trial='Halt the Tilt',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Faron',
    lat=-3615,
    long=1587,
),
Shrine(
    id=38,
    name='Shoda Sah',
    trial='Impeccable Timing',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Faron',
    lat=-2992,
    long=1790,
),
Shrine(
    id=39,
    name='Kah Yah',
    trial='Quick Thinking',
    quest='A Fragmented Monument',
    blessing=False,
    tos=None,
    beast=None,
    region='Faron',
    lat=-3316,
    long=3437,
),
Shrine(
    id=40,
    name='Qukah Nata',
    trial="Qukah Nata's Blessing",
    quest='A Song of Storms',
    blessing=True,
    tos=None,
    beast=None,
    region='Faron',
    lat=-3285,
    long=2007,
),
Shrine(
    id=41,
    name='Tawa Jinn',
    trial="Tawa Jinn's Blessing",
    quest='The Three Giant Brothers',
    blessing=True,
    tos=None,
    beast=None,
    region='Faron',
    lat=-2834,
    long=2638,
),
Shrine(
    id=42,
    name='Kema Kosassa',
    trial='A Major Test of Strength',
    quest=None,
    blessing=False,
    tos='major',
    beast=None,
    region='Gerudo',
    lat=-905,
    long=-4658,
),
Shrine(
    id=43,
    name='Dah Kaso',
    trial='A Minor Test of Strength',
    quest=None,
    blessing=False,
    tos='minor',
    beast=None,
    region='Gerudo',
    lat=-1700,
    long=-1695,
),
Shrine(
    id=44,
    name='Sasa Kai',
    trial='A Modest Test of Strength',
    quest='Sign of the Shadow',
    blessing=False,
    tos='modest',
    beast=None,
    region='Gerudo',
    lat=-1953,
    long=-3560,
),
Shrine(
    id=45,
    name='Joloo Nah',
    trial='Joloo Nah Apparatus',
    quest='Test of Will',
    blessing=False,
    tos=None,
    beast=None,
    region='Gerudo',
    lat=-1674,
    long=-2004,
),
Shrine(
    id=46,
    name='Keeha Yoog',
    trial="Keeha Yoog's Blessing",
    quest='Cliffside Etchings',
    blessing=True,
    tos=None,
    beast=None,
    region='Gerudo',
    lat=-717,
    long=-3853,
),
Shrine(
    id=47,
    name='Kuh Takkar',
    trial='Melting Ice Hazard',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Gerudo',
    lat=-1221,
    long=-3083,
),
Shrine(
    id=48,
    name='Sho Dantu',
    trial='Two Bombs',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Gerudo',
    lat=-1654,
    long=-3911,
),
Shrine(
    id=49,
    name='Chaas Qeta',
    trial='A Major Test of Strength',
    quest=None,
    blessing=False,
    tos='major',
    beast=None,
    region='Hateno',
    lat=-2991,
    long=4012,
),
Shrine(
    id=50,
    name='Mezza Lo',
    trial='Ancient Trifecta',
    quest='The Crowned Beast',
    blessing=False,
    tos=None,
    beast=None,
    region='Hateno',
    lat=-378,
    long=2622,
),
Shrine(
    id=51,
    name="Jitan Sa'mi",
    trial="Jitan Sa'mi's Blessing",
    quest='The Spring of Wisdom',
    blessing=True,
    tos=None,
    beast=None,
    region='Hateno',
    lat=-1315,
    long=3882,
),
Shrine(
    id=52,
    name='Myahm Agana',
    trial='Myahm Agana Apparatus',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Hateno',
    lat=-2216,
    long=3388,
),
Shrine(
    id=53,
    name="Tahno O'ah",
    trial="Tahno O'ah's Blessing",
    quest='Secret of the Cedars',
    blessing=True,
    tos=None,
    beast=None,
    region='Hateno',
    lat=-1687,
    long=4182,
),
Shrine(
    id=54,
    name="Dow Na'eh",
    trial='Three Boxes',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Hateno',
    lat=-1333,
    long=2698,
),
Shrine(
    id=55,
    name='Kam Urog',
    trial='Trial of Passage',
    quest='The Cursed Statue',
    blessing=False,
    tos=None,
    beast=None,
    region='Hateno',
    lat=-1495,
    long=2501,
),
Shrine(
    id=56,
    name='Goma Asaagh',
    trial='A Major Test of Strength',
    quest=None,
    blessing=False,
    tos='major',
    beast=None,
    region='Hebra',
    lat=2882,
    long=-2792,
),
Shrine(
    id=57,
    name='Hia Miu',
    trial='A Major Test of Strength',
    quest=None,
    blessing=False,
    tos='major',
    beast=None,
    region='Hebra',
    lat=3803,
    long=-4447,
),
Shrine(
    id=58,
    name='Mozo Shenno',
    trial='A Major Test of Strength',
    quest='The Bird in the Mountains',
    blessing=False,
    tos='major',
    beast=None,
    region='Hebra',
    lat=3038,
    long=-3628,
),
Shrine(
    id=59,
    name='Dunba Taag',
    trial='Build and Release',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Hebra',
    lat=1578,
    long=-2832,
),
Shrine(
    id=60,
    name='Rin Oyaa',
    trial='Directing the Wind',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Hebra',
    lat=2554,
    long=-1721,
),
Shrine(
    id=61,
    name='Lanno Kooh',
    trial="Lanno Kooh's Blessing",
    quest=None,
    blessing=True,
    tos=None,
    beast=None,
    region='Hebra',
    lat=2060,
    long=-2636,
),
Shrine(
    id=62,
    name='Rok Uwog',
    trial='Power of Reach',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Hebra',
    lat=3225,
    long=-2378,
),
Shrine(
    id=63,
    name='Qaza Tokki',
    trial="Qaza Tokki's Blessing",
    quest='Trial on the Cliff',
    blessing=True,
    tos=None,
    beast=None,
    region='Hebra',
    lat=3535,
    long=-821,
),
Shrine(
    id=64,
    name='Shada Naw',
    trial='Red Giveaway',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Hebra',
    lat=3222,
    long=-2999,
),
Shrine(
    id=65,
    name='Sha Gehma',
    trial='Shift and Lock',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Hebra',
    lat=3758,
    long=-1673,
),
Shrine(
    id=66,
    name='Maka Rah',
    trial='Steady Thy Heart',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Hebra',
    lat=2508,
    long=-4058,
),
Shrine(
    id=67,
    name="Gee Ha'rah",
    trial='Tandem',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Hebra',
    lat=2255,
    long=-2380,
),
Shrine(
    id=68,
    name='To Quomo',
    trial="To Quomo's Blessing",
    quest=None,
    blessing=True,
    tos=None,
    beast=None,
    region='Hebra',
    lat=3712,
    long=-4023,
),
Shrine(
    id=69,
    name='Pumaag Nitae',
    trial='A Minor Test of Strength',
    quest=None,
    blessing=False,
    tos='minor',
    beast=None,
    region='Lake',
    lat=-2990,
    long=559,
),
Shrine(
    id=70,
    name='Shoqa Tatone',
    trial='A Modest Test of Strength',
    quest='Guardian Slideshow',
    blessing=False,
    tos='modest',
    beast=None,
    region='Lake',
    lat=-3842,
    long=94,
),
Shrine(
    id=71,
    name='Ishto Soh',
    trial="Bravery's Grasp",
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Lake',
    lat=-3565,
    long=-985,
),
Shrine(
    id=72,
    name="Ka'o Makagh",
    trial='Metal Doors Open the Way',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Lake',
    lat=-3526,
    long=523,
),
Shrine(
    id=73,
    name='Shae Katha',
    trial="Shae Katha's Blessing",
    quest="The Serpent's Jaws",
    blessing=True,
    tos=None,
    beast=None,
    region='Lake',
    lat=-2329,
    long=870,
),
Shrine(
    id=74,
    name='Ya Naga',
    trial='Shatter the Heavens',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Lake',
    lat=-2600,
    long=-328,
),
Shrine(
    id=75,
    name='Soh Kofi',
    trial='A Minor Test of Strength',
    quest=None,
    blessing=False,
    tos='minor',
    beast=None,
    region='Lanayru',
    lat=293,
    long=2238,
),
Shrine(
    id=76,
    name='Dagah Keek',
    trial="Dagah Keek's Blessing",
    quest='The Ceremonial Song',
    blessing=True,
    tos=None,
    beast=None,
    region='Lanayru',
    lat=417,
    long=3150,
),
Shrine(
    id=77,
    name='Kah Mael',
    trial='Drop and Rise',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Lanayru',
    lat=1310,
    long=4709,
),
Shrine(
    id=78,
    name='Rucco Maag',
    trial='Five Flames',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Lanayru',
    lat=-402,
    long=3334,
),
Shrine(
    id=79,
    name="Ne'ez Yohma",
    trial='Pushing Power',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Lanayru',
    lat=519,
    long=3324,
),
Shrine(
    id=80,
    name='Shai Yota',
    trial="Shai Yota's Blessing",
    quest='Master of the Wind',
    blessing=True,
    tos=None,
    beast=None,
    region='Lanayru',
    lat=-253,
    long=4246,
),
Shrine(
    id=81,
    name='Sheh Rata',
    trial='Speed of Light',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Lanayru',
    lat=377,
    long=1510,
),
Shrine(
    id=82,
    name='Daka Tuss',
    trial='Sunken Scoop',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Lanayru',
    lat=-462,
    long=1601,
),
Shrine(
    id=83,
    name='Mijah Rokee',
    trial='A Modest Test of Strength',
    quest='Under a Red Moon',
    blessing=False,
    tos='modest',
    beast=None,
    region='Ridgeland',
    lat=-226,
    long=-2734,
),
Shrine(
    id=84,
    name='Shae Loya',
    trial='Aim for the Moment',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Ridgeland',
    lat=432,
    long=-2931,
),
Shrine(
    id=85,
    name='Toh Yahsa',
    trial='Buried Secrets',
    quest='Trial of Thunder',
    blessing=False,
    tos=None,
    beast=None,
    region='Ridgeland',
    lat=900,
    long=-2269,
),
Shrine(
    id=86,
    name="Maag No'rah",
    trial="Maag No'rah's Blessing",
    quest=None,
    blessing=True,
    tos=None,
    beast=None,
    region='Ridgeland',
    lat=1458,
    long=-1940,
),
Shrine(
    id=87,
    name='Sheem Dagoze',
    trial='Moving in Parallel',
    quest='The Two Rings',
    blessing=False,
    tos=None,
    beast=None,
    region='Ridgeland',
    lat=-92,
    long=-1893,
),
Shrine(
    id=88,
    name='Mogg Latan',
    trial='Synced Swing',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Ridgeland',
    lat=-461,
    long=-2297,
),
Shrine(
    id=89,
    name='Zalta Wa',
    trial='Two Orbs to Guide You',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Ridgeland',
    lat=594,
    long=-1432,
),
Shrine(
    id=90,
    name="Tena Ko'sah",
    trial='A Major Test of Strength',
    quest=None,
    blessing=False,
    tos='major',
    beast=None,
    region='Tabantha',
    lat=448,
    long=-3465,
),
Shrine(
    id=91,
    name='Bareeda Naag',
    trial='Cannon',
    quest='The Ancient Rito Song',
    blessing=False,
    tos=None,
    beast=None,
    region='Tabantha',
    lat=1515,
    long=-3609,
),
Shrine(
    id=92,
    name='Sha Warvo',
    trial='Path of Hidden Winds',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Tabantha',
    lat=2206,
    long=-3823,
),
Shrine(
    id=93,
    name='Voo Lota',
    trial='The Winding Route',
    quest="Recital at Warbler's Nest",
    blessing=False,
    tos=None,
    beast='medoh',
    region='Tabantha',
    lat=1722,
    long=-4016,
),
Shrine(
    id=94,
    name='Kah Okeo',
    trial='Wind Guide',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Tabantha',
    lat=414,
    long=-4120,
),
Shrine(
    id=95,
    name="Akh Va'quot",
    trial='Windmills',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Tabantha',
    lat=1757,
    long=-3656,
),
Shrine(
    id=96,
    name='Kema Zoos',
    trial='A Delayed Puzzle',
    quest='The Silent Swordswomen',
    blessing=False,
    tos=None,
    beast=None,
    region='Wasteland',
    lat=-1968,
    long=-4674,
),
Shrine(
    id=97,
    name='Dila Maag',
    trial="Dila Maag's Blessing",
    quest='The Desert Labyrinth',
    blessing=True,
    tos=None,
    beast=None,
    region='Wasteland',
    lat=-3465,
    long=-1795,
),
Shrine(
    id=98,
    name='Dako Tah',
    trial='Electric Path',
    quest='The Eye of the Sandstorm',
    blessing=False,
    tos=None,
    beast=None,
    region='Wasteland',
    lat=-2162,
    long=-3318,
),
Shrine(
    id=99,
    name="Korsh O'hu",
    trial="Korsh O'hu's Blessing",
    quest='The Seven Heroines',
    blessing=True,
    tos=None,
    beast=None,
    region='Wasteland',
    lat=-2811,
    long=-2689,
),
Shrine(
    id=100,
    name='Misae Suma',
    trial="Misae Suma's Blessing",
    quest='The Perfect Drink',
    blessing=True,
    tos=None,
    beast=None,
    region='Wasteland',
    lat=-3782,
    long=-2970,
),
Shrine(
    id=101,
    name='Jee Noh',
    trial='On the Move',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Wasteland',
    lat=-2423,
    long=-1793,
),
Shrine(
    id=102,
    name='Kay Noh',
    trial='Power of Electricity',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Wasteland',
    lat=-2300,
    long=-2810,
),
Shrine(
    id=103,
    name='Raqa Zunzo',
    trial="Raqa Zunzo's Blessing",
    quest='The Undefeated Champ',
    blessing=True,
    tos=None,
    beast='naboris',
    region='Wasteland',
    lat=-3127,
    long=-3811,
),
Shrine(
    id=104,
    name='Suma Sahma',
    trial="Suma Sahma's Blessing",
    quest='Secret of the Snowy Peaks',
    blessing=True,
    tos=None,
    beast=None,
    region='Wasteland',
    lat=-3448,
    long=-1418,
),
Shrine(
    id=105,
    name='Hawa Koth',
    trial='The Current Solution',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Wasteland',
    lat=-3773,
    long=-4847,
),
Shrine(
    id=106,
    name='Daqo Chisay',
    trial='The Whole Picture',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Wasteland',
    lat=-2820,
    long=-3817,
),
Shrine(
    id=107,
    name='Tho Kayu',
    trial="Tho Kayu's Blessing",
    quest=None,
    blessing=True,
    tos=None,
    beast=None,
    region='Wasteland',
    lat=-2800,
    long=-4799,
),
Shrine(
    id=108,
    name='Daag Chokah',
    trial="Daag Chokah's Blessing",
    quest='The Lost Pilgrimage',
    blessing=True,
    tos=None,
    beast=None,
    region='Woodland',
    lat=2459,
    long=-26,
),
Shrine(
    id=109,
    name='Monya Toma',
    trial='Drawing Parabolas',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Woodland',
    lat=1473,
    long=-1489,
),
Shrine(
    id=110,
    name='Keo Ruug',
    trial='Fateful Stars',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Woodland',
    lat=2169,
    long=471,
),
Shrine(
    id=111,
    name='Ketoh Wawai',
    trial="Ketoh Wawai's Blessing",
    quest='Shrouded Shrine',
    blessing=True,
    tos=None,
    beast=None,
    region='Woodland',
    lat=3120,
    long=283,
),
Shrine(
    id=112,
    name='Kuhn Sidajj',
    trial="Kuh Sidajj's Blessing",
    quest='Trial of Second Sight',
    blessing=True,
    tos=None,
    beast=None,
    region='Woodland',
    lat=1944,
    long=18,
),
Shrine(
    id=113,
    name='Maag Halan',
    trial="Maag Halan's Blessing",
    quest='The Test of Wood',
    blessing=True,
    tos=None,
    beast=None,
    region='Woodland',
    lat=2420,
    long=837,
),
Shrine(
    id=114,
    name='Rona Kachta',
    trial="Rona Kachta's Blessing",
    quest=None,
    blessing=True,
    tos=None,
    beast=None,
    region='Woodland',
    lat=2662,
    long=-1088,
),
Shrine(
    id=115,
    name='Mirro Shaz',
    trial='Tempered Power',
    quest=None,
    blessing=False,
    tos=None,
    beast=None,
    region='Woodland',
    lat=1213,
    long=1232,
)
]
